Repository eodya/eodya-backend, pull requests merged in 2024-03, with the labels that each got.

#2 build: Spring Client 의존성 설정
  build.gradle
  src/main/resources/application.properties
  src/main/resources/bootstrap-dev.yaml
  src/main/resources/bootstrap-prod.yaml
  src/test/resources/bootstrap-test.yaml
Labels: 빌드

#4 [#2] PR 컨벤션에 따라, 로컬 작업 시 환경설정 변경방지를 위한 .gitignore 추가
  .gitignore
Labels: 기타, 빌드

#13 [#9] 엔티티 설계 및 엔티티 테스트 코드 부분 작성
  build.gradle
  src/main/java/com/eodya/api/common/entity/BaseEntity.java
  src/main/java/com/eodya/api/entity/AddressDepth1.java
  src/main/java/com/eodya/api/entity/AddressDepth2.java
  src/main/java/com/eodya/api/entity/Bookmark.java
  src/main/java/com/eodya/api/entity/Place.java
  src/main/java/com/eodya/api/entity/PlaceStatus.java
  src/main/java/com/eodya/api/entity/PlaceTag.java
  src/main/java/com/eodya/api/entity/Recommendation.java
  src/main/java/com/eodya/api/entity/Review.java
  src/main/java/com/eodya/api/entity/User.java
  src/main/resources/bootstrap-dev.yaml
  src/main/resources/bootstrap-prod.yaml
  src/test/java/com/eodya/api/domain/AddressDepthTest.java
  src/test/java/com/eodya/api/domain/PlaceTagTest.java
  src/test/java/com/eodya/api/domain/PlaceTest.java
  src/test/java/com/eodya/api/domain/UserTest.java
  src/test/java/com/eodya/api/fixture/domain/AddressDepthFixture.java
  src/test/java/com/eodya/api/fixture/domain/PlaceFixture.java
  src/test/java/com/eodya/api/fixture/domain/PlaceTagFixture.java
  src/test/java/com/eodya/api/fixture/domain/UserFixture.java
  src/test/resources/bootstrap-test.yaml
Labels: 신규 기능, 테스트

#19 [#18]추천 생성/취소 API 로직 구현, 추천 도메인 에러 처리 로직 구현, Converter 적용
  src/main/java/com/eodya/api/common/exception/GlobalExceptionHandler.java
  src/main/java/com/eodya/api/recommendation/controller/RecommendationController.java
  src/main/java/com/eodya/api/recommendation/domain/Recommendation.java
  src/main/java/com/eodya/api/recommendation/domain/RecommendationStatus.java
  src/main/java/com/eodya/api/recommendation/dto/request/RecommendationChangeStatusRequest.java
  src/main/java/com/eodya/api/recommendation/exception/RecommendationException.java
  src/main/java/com/eodya/api/recommendation/exception/RecommendationExceptionCode.java
  src/main/java/com/eodya/api/recommendation/repository/RecommendationRepository.java
  src/main/java/com/eodya/api/recommendation/service/RecommendationService.java
  src/main/java/com/eodya/api/recommendation/util/RecommendationStatusAttributeConverter.java
  src/main/java/com/eodya/api/recommendation/util/RecommendationStatusConverter.java
  src/main/java/com/eodya/api/review/domain/Review.java
  src/main/java/com/eodya/api/users/config/Login.java
  src/main/resources/db/migration/V1.0_Init.sql
Labels: 신규 기능, 리팩토링

#23 [#22] Spring Cloud Client 환경별 (prod-배포, dev-개발, test-테스트) 환경세팅이 되지 않는 트러블 슈팅 해결
  src/main/resources/application.yaml
  src/test/resources/application.yaml
  src/test/resources/bootstrap-test.yaml
Labels: 버그

#34 [#30] 장소 후기 목록 조회 API 구현
  src/main/java/com/eodya/api/review/controller/ReviewController.java
  src/main/java/com/eodya/api/review/dto/response/ReviewDetail.java
  src/main/java/com/eodya/api/review/dto/response/ReviewProfileResponse.java
  src/main/java/com/eodya/api/review/repository/ReviewRepository.java
  src/main/java/com/eodya/api/review/service/ReviewService.java
  src/main/resources/application.yml
Labels: 신규 기능

#36 [#33] 장소 등록 API개발, @Transactional추가
  src/main/java/com/eodya/api/place/controller/PlaceController.java
  src/main/java/com/eodya/api/place/dto/request/PlaceCreateRequest.java
  src/main/java/com/eodya/api/place/repository/AddressDepth1Repository.java
  src/main/java/com/eodya/api/place/repository/AddressDepth2Repository.java
  src/main/java/com/eodya/api/place/service/PlaceService.java
  src/main/java/com/eodya/api/review/domain/Review.java
  src/main/java/com/eodya/api/review/domain/ReviewImage.java
  src/main/java/com/eodya/api/users/service/UserService.java
Labels: 신규 기능

#37 [#35] 북마크 기준 장소 랭킹 조회
  src/main/java/com/eodya/api/place/controller/PlaceController.java
  src/main/java/com/eodya/api/place/dto/response/PlaceRakingResponse.java
  src/main/java/com/eodya/api/place/repository/PlaceRepository.java
  src/main/java/com/eodya/api/place/service/PlaceService.java
  src/main/java/com/eodya/api/ranking/controller/RankingController.java
  src/main/java/com/eodya/api/ranking/dto/RankingResponse.java
  src/main/java/com/eodya/api/ranking/repository/RankingRepository.java
  src/main/java/com/eodya/api/ranking/service/RankingService.java
  src/main/java/com/eodya/api/review/domain/Review.java
Labels: 신규 기능

#41 [#40] 태그에 맞는 모든 장소 불러오기 API
  src/main/java/com/eodya/api/place/controller/PlaceController.java
  src/main/java/com/eodya/api/place/dto/response/PlaceAllByTagResponse.java
  src/main/java/com/eodya/api/place/repository/PlaceRepository.java
  src/main/java/com/eodya/api/place/repository/PlaceTagRepository.java
  src/main/java/com/eodya/api/place/service/PlaceService.java
Labels: 신규 기능

#44 [#43] Swagger 설정 추가
  build.gradle
  src/main/java/com/eodya/api/common/config/SwaggerConfig.java
Labels: 문서

#57 [#56] 세부 장소 api개발
  src/main/java/com/eodya/api/place/controller/PlaceController.java
  src/main/java/com/eodya/api/place/dto/response/PlaceDetailResponse.java
  src/main/java/com/eodya/api/place/service/PlaceService.java
Labels: 신규 기능

#61 [#60] placeDetail api수정
  src/main/java/com/eodya/api/bookmark/repository/BookmarkRepository.java
  src/main/java/com/eodya/api/place/controller/PlaceController.java
  src/main/java/com/eodya/api/place/dto/response/PlaceDetailResponse.java
  src/main/java/com/eodya/api/place/service/PlaceService.java
Labels: 버그

#59 [#58] 북마크 카운터 수정
  src/main/java/com/eodya/api/place/dto/response/PlaceDetailResponse.java
  src/main/java/com/eodya/api/place/repository/PlaceRepository.java
  src/main/java/com/eodya/api/place/service/PlaceService.java
Labels: 버그
